name: Generate

on:
    push:
        branches:
            - main
        tags:
            - 'v*'
    schedule:
        # https://crontab.guru/
        # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
        - cron: '30 0/3 * * *'
    workflow_dispatch:

jobs:
    generate:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
            - run: npm ci
            - name: Generate assets
              run: npm run generate
              env:
                  # Use a PAT here. The default GITHUB_TOKEN only has access to this repository.
                  PROFILE_GITHUB_TOKEN: ${{ secrets.PROFILE_GITHUB_TOKEN || secrets.RELEASE }}

            - name: Release branch
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ github.token }}
                  publish_branch: release
                  publish_dir: ./output
